
import React, { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { BookOpen, Brain, Calculator, CheckCircle2, ClipboardList, Download, Ear, Eye, EyeOff, History, Lightbulb, ListChecks, Lock, PenLine, Rocket, Search, Sparkles, Target, Trash2, UserRound, Volume2, Zap } from "lucide-react";
import { derivativeExercises, functionExercises, readingTexts, planningTasks, memoryTasks, attentionTasks, audioTasks } from "./data.js";

function csvEscape(value){const text=String(value??"");return `"${text.replace(/"/g,'""')}"`;}
function safeReadSessions(){try{return JSON.parse(localStorage.getItem("portal_sessions")||"[]")}catch{return[]}}
function getSheetsUrl(){return localStorage.getItem("google_sheets_web_app_url")||""}
function setSheetsUrl(url){localStorage.setItem("google_sheets_web_app_url",url.trim())}
function getPatientCode(){return localStorage.getItem("portal_patient_code")||""}
function savePatientCode(code){localStorage.setItem("portal_patient_code",code.trim())}

function buildRows({session,module,activityTitle,activityNumber,answers,score="",maxScore="",metadata={}}){
  return Object.entries(answers).map(([field,answer])=>({session_id:session.id,fecha:session.date,paciente:session.patientCode,modulo:module,actividad_numero:activityNumber,actividad_titulo:activityTitle,campo:field,respuesta:answer,score,max_score:maxScore,metadata}));
}
function saveSession({module,activityTitle,activityNumber,answers,score="",maxScore="",metadata={}}){
  const previous=safeReadSessions();
  const session={id:Date.now(),date:new Date().toLocaleString(),patientCode:getPatientCode(),module,activityTitle,activityNumber,answers,score,maxScore,metadata};
  const rows=buildRows({session,module,activityTitle,activityNumber,answers,score,maxScore,metadata});
  const stored={...session,rows};
  localStorage.setItem("portal_sessions",JSON.stringify([stored,...previous]));
  return stored;
}
function buildCsvFromSessions(sessions){
  const headers=["session_id","fecha","paciente","modulo","actividad_numero","actividad_titulo","campo","respuesta","score","max_score","metadata"];
  const rows=sessions.flatMap((session)=>session.rows||[]);
  return [headers,...rows.map((row)=>headers.map((h)=>row[h]??""))].map((row)=>row.map(csvEscape).join(",")).join("\n");
}
async function sendSessionToGoogleSheets(session){
  const url=getSheetsUrl();
  if(!url)return{ok:false,message:"No hay URL de Google Sheets configurada."};
  try{
    await fetch(url,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({session,rows:session.rows||[]})});
    return{ok:true,message:"Sesión enviada a Google Sheets."};
  }catch(error){return{ok:false,message:`No se pudo enviar a Google Sheets: ${error.message}`}}
}
function Button({children,className="",variant="plain",...props}){return <button className={`btn ${variant} ${className}`} {...props}>{children}</button>}
function MathDoodle(){return <motion.div className="doodle" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}}><motion.div className="doodle-fx" animate={{y:[0,-8,0]}} transition={{repeat:Infinity,duration:3}}>f(x)</motion.div><motion.div className="doodle-dot" animate={{x:[0,10,0]}} transition={{repeat:Infinity,duration:3.5}}/><motion.div className="doodle-line" animate={{rotate:[-6,6,-6]}} transition={{repeat:Infinity,duration:2.8}}>y = mx + b</motion.div></motion.div>}
function SectionTitle({icon:Icon,title,subtitle}){return <div className="section-title"><div className="section-heading"><motion.div className="icon-box" whileHover={{rotate:-8,scale:1.05}}><Icon size={25}/></motion.div><div><h2>{title}</h2><p className="section-subtitle">{subtitle}</p></div></div><MathDoodle/></div>}
function LoginGate({onLogin}){const[code,setCode]=useState(getPatientCode());const submit=()=>{if(!code.trim())return alert("Introduce un código de paciente.");savePatientCode(code);onLogin(code.trim())};return <div className="login-wrap"><motion.div className="card login-card" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}><div className="icon-box"><Lock size={26}/></div><h1>Acceso del paciente</h1><p>Introduce tu código para guardar las respuestas correctamente.</p><label><span>Código de paciente</span><input value={code} onChange={(e)=>setCode(e.target.value)} placeholder="Ej.: PACIENTE-001"/></label><div style={{marginTop:16}}><Button variant="primary" onClick={submit}><UserRound size={18}/> Entrar</Button></div></motion.div></div>}

function Explanation(){return <section className="section"><SectionTitle icon={Lightbulb} title="1. Funciones y derivadas" subtitle="Qué son, para qué sirven y dónde aparecen en la vida diaria."/><div className="grid-2"><motion.div whileHover={{y:-4}} className="card"><h3>¿Qué es una función?</h3><p>Una función relaciona una entrada con una salida. Sirve para modelar precios, distancias, consumos, notas o ingresos.</p><div className="info amber"><b>Ejemplo:</b> precio = parte fija + precio por kilómetro.</div></motion.div><motion.div whileHover={{y:-4}} className="card"><h3>¿Qué es una derivada?</h3><p>La derivada mide cómo cambia una función en un punto. Sirve para velocidades, ritmos de cambio, máximos y mínimos.</p><div className="info green"><b>Ejemplo:</b> si una función da posición, su derivada da velocidad.</div></motion.div></div><div className="card" style={{marginTop:18}}><h3>Métodos de derivación</h3><div className="grid-3">{["Constante","Potencia","Suma/resta","Producto","Cociente","Cadena","Trigonométricas","Exponenciales","Logaritmos"].map((item)=><div className="mini-card" key={item}><b>{item}</b><p>Identifica la forma de la función y aplica la regla correspondiente.</p></div>)}</div></div></section>}
function Algorithms(){const f=["Leer el enunciado","Identificar qué se pide","Sustituir valores","Revisar restricciones","Calcular cortes","Comprobar unidades"];const d=["Simplificar","Identificar regla","Derivar término a término","Aplicar producto/cociente/cadena","Igualar a 0 si buscas máximos","Simplificar"];return <section className="section"><SectionTitle icon={Brain} title="2. Algoritmos" subtitle="Rutas paso a paso."/><div className="grid-2"><div className="card"><h3>Funciones</h3>{f.map((s,i)=><p key={s}><b>{i+1}.</b> {s}</p>)}</div><div className="card"><h3>Derivadas</h3>{d.map((s,i)=><p key={s}><b>{i+1}.</b> {s}</p>)}</div></div></section>}
function MathPractice(){const[shown,setShown]=useState({});const all=[...functionExercises.map((e,i)=>({kind:"Funciones",n:i+1,...e})),...derivativeExercises.map((e,i)=>({kind:"Derivadas",n:i+1,...e}))];return <section className="section"><SectionTitle icon={Calculator} title="3. Ejercicios matemáticos" subtitle="Funciones y derivadas con solución explicada."/><div className="exercise-grid">{all.map((ex,i)=><motion.div className="exercise-card" key={`${ex.kind}-${ex.n}`} whileHover={{y:-3}}><div className="exercise-top"><span className={`pill ${ex.kind==="Funciones"?"function":"derivative"}`}>{ex.kind} {ex.n}</span><Button onClick={()=>setShown({...shown,[i]:!shown[i]})}>{shown[i]?<EyeOff size={16}/>:<Eye size={16}/>} {shown[i]?"Ocultar":"Ver solución"}</Button></div><p><b>{ex.q}</b></p>{shown[i]&&<motion.div className="solution" initial={{opacity:0,y:-5}} animate={{opacity:1,y:0}}><b>Solución:</b> {ex.a}<br/><br/><b>Por qué:</b> {ex.explanation}</motion.div>}</motion.div>)}</div></section>}
function InputArea({label,value,onChange}){return <label><span>{label}</span><textarea value={value} onChange={(e)=>onChange(e.target.value)} placeholder="Escribe aquí tu respuesta..."/></label>}

function Reading(){const[selected,setSelected]=useState(0);const[answers,setAnswers]=useState({});const[status,setStatus]=useState("");const text=readingTexts[selected];const update=(field,value)=>setAnswers({...answers,[`${selected}_${field}`]:value});const save=async()=>{const session=saveSession({module:"lectura",activityTitle:text.title,activityNumber:selected+1,answers,metadata:{type:text.type}});setStatus("Guardando y enviando...");const result=await sendSessionToGoogleSheets(session);setStatus(result.message);};return <section className="section"><SectionTitle icon={BookOpen} title="4. Lectura comprensiva" subtitle="Textos con preguntas, gramática e ideas principales."/><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}>{readingTexts.map((item,i)=><Button key={item.title} variant={i===selected?"primary":"outline"} onClick={()=>setSelected(i)}>{i+1}</Button>)}</div><div className="card"><p><span className="pill function">{text.type}</span></p><h3>{text.title}</h3><div className="text-card">{`${text.text}\n\n${text.extension}`}</div><div className="form-grid"><InputArea label="Título alternativo" value={answers[`${selected}_titulo`]||""} onChange={(v)=>update("titulo",v)}/><InputArea label="Resumen" value={answers[`${selected}_resumen`]||""} onChange={(v)=>update("resumen",v)}/><InputArea label="Ideas principales" value={answers[`${selected}_ideas`]||""} onChange={(v)=>update("ideas",v)}/><InputArea label="Opinión" value={answers[`${selected}_opinion`]||""} onChange={(v)=>update("opinion",v)}/><InputArea label={`Categoría gramatical: ${text.words.join(", ")}`} value={answers[`${selected}_gramatica`]||""} onChange={(v)=>update("gramatica",v)}/></div><div style={{marginTop:18,textAlign:"right"}}><Button variant="primary" onClick={save}><CheckCircle2 size={18}/> Guardar lectura</Button>{status&&<p>{status}</p>}</div></div></section>}

function Planning(){const[selected,setSelected]=useState(0);const[orders,setOrders]=useState({});const[answers,setAnswers]=useState({});const[status,setStatus]=useState("");const task=planningTasks[selected];const save=async()=>{const orderValues=task.steps.map((_,i)=>Number(orders[i]||0));const correct=orderValues.filter((v,i)=>v===i+1).length;const session=saveSession({module:"planificacion",activityTitle:task.title,activityNumber:selected+1,answers:{orden:orderValues.join(", "),...answers},score:correct,maxScore:task.steps.length,metadata:{expectedSteps:task.steps}});setStatus("Guardando y enviando...");const result=await sendSessionToGoogleSheets(session);setStatus(result.message);};return <section className="section"><SectionTitle icon={ListChecks} title="5. Planificación" subtitle="Organizar actividades de la vida diaria."/><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}>{planningTasks.map((item,i)=><Button key={item.title} variant={i===selected?"primary":"outline"} onClick={()=>setSelected(i)}>{i+1}</Button>)}</div><div className="card"><h3>{task.title}</h3><p>{task.context}</p><p><b>Ordena los pasos escribiendo 1, 2, 3...</b></p><div className="sequence-grid">{task.steps.map((step,i)=><div className="sequence-item" key={step}><input value={orders[i]||""} onChange={(e)=>setOrders({...orders,[i]:e.target.value})}/><span>{step}</span></div>)}</div><div className="form-grid">{task.questions.map((q,i)=><InputArea key={q} label={q} value={answers[`pregunta_${i+1}`]||""} onChange={(v)=>setAnswers({...answers,[`pregunta_${i+1}`]:v})}/>)}</div><div style={{marginTop:18,textAlign:"right"}}><Button variant="primary" onClick={save}>Guardar planificación</Button>{status&&<p>{status}</p>}</div></div></section>}

function Memory(){const[selected,setSelected]=useState(0);const[visible,setVisible]=useState(true);const[answer,setAnswer]=useState("");const[status,setStatus]=useState("");const task=memoryTasks[selected];const save=async()=>{const normalized=answer.toLowerCase();const score=task.items.filter((item)=>normalized.includes(item.toLowerCase())).length;const session=saveSession({module:"memoria",activityTitle:task.title,activityNumber:selected+1,answers:{recuerdo:answer},score,maxScore:task.items.length,metadata:{targetItems:task.items}});setStatus("Guardando y enviando...");const result=await sendSessionToGoogleSheets(session);setStatus(result.message);};return <section className="section"><SectionTitle icon={Brain} title="6. Memoria" subtitle="Recordar listas, recados y secuencias."/><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}>{memoryTasks.map((item,i)=><Button key={item.title} variant={i===selected?"primary":"outline"} onClick={()=>{setSelected(i);setAnswer("");setVisible(true)}}>{i+1}</Button>)}</div><div className="card"><h3>{task.title}</h3><p>{task.prompt}</p><Button variant="outline" onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={16}/>:<Eye size={16}/>} {visible?"Ocultar lista":"Ver lista"}</Button>{visible&&<div className="info pink" style={{marginTop:12}}><b>{task.items.join(" · ")}</b></div>}<div className="form-grid"><InputArea label="Escribe lo que recuerdas" value={answer} onChange={setAnswer}/></div><div style={{marginTop:18,textAlign:"right"}}><Button variant="primary" onClick={save}>Guardar memoria</Button>{status&&<p>{status}</p>}</div></div></section>}

function Attention(){const[selected,setSelected]=useState(0);const[answer,setAnswer]=useState("");const[status,setStatus]=useState("");const task=attentionTasks[selected];const save=async()=>{const score=Number(answer)===task.answer?1:0;const session=saveSession({module:"atencion",activityTitle:task.title,activityNumber:selected+1,answers:{objetivo:task.target,respuesta:answer},score,maxScore:1,metadata:{sequence:task.sequence,expected:task.answer}});setStatus("Guardando y enviando...");const result=await sendSessionToGoogleSheets(session);setStatus(result.message);};return <section className="section"><SectionTitle icon={Search} title="7. Atención" subtitle="Búsqueda visual y concentración."/><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}>{attentionTasks.map((item,i)=><Button key={item.title} variant={i===selected?"primary":"outline"} onClick={()=>{setSelected(i);setAnswer("")}}>{i+1}</Button>)}</div><div className="card"><h3>{task.title}</h3><p>Cuenta cuántas veces aparece: <span className="pill attention">{task.target}</span></p><div className="text-card" style={{fontSize:"1.35rem",letterSpacing:".12em"}}>{task.sequence}</div><label style={{marginTop:16}}><span>Respuesta</span><input value={answer} onChange={(e)=>setAnswer(e.target.value)} placeholder="Número de apariciones"/></label><div style={{marginTop:18,textAlign:"right"}}><Button variant="primary" onClick={save}>Guardar atención</Button>{status&&<p>{status}</p>}</div></div></section>}

function AudioExercises(){const[selected,setSelected]=useState(0);const[answers,setAnswers]=useState({});const[status,setStatus]=useState("");const task=audioTasks[selected];const speak=()=>{if(!("speechSynthesis" in window))return alert("Este navegador no permite lectura en voz alta.");window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(task.text);u.lang="es-ES";u.rate=.92;window.speechSynthesis.speak(u)};const save=async()=>{const session=saveSession({module:"audio",activityTitle:task.title,activityNumber:selected+1,answers,metadata:{listenedText:task.text,questions:task.questions}});setStatus("Guardando y enviando...");const result=await sendSessionToGoogleSheets(session);setStatus(result.message);};return <section className="section"><SectionTitle icon={Ear} title="8. Audio y comprensión oral" subtitle="Escuchar instrucciones y responder preguntas."/><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}>{audioTasks.map((item,i)=><Button key={item.title} variant={i===selected?"primary":"outline"} onClick={()=>{setSelected(i);setAnswers({})}}>{i+1}</Button>)}</div><div className="card"><h3>{task.title}</h3><Button variant="good" onClick={speak}><Volume2 size={18}/> Escuchar audio</Button><div className="form-grid">{task.questions.map((q,i)=><InputArea key={q} label={q} value={answers[`pregunta_${i+1}`]||""} onChange={(v)=>setAnswers({...answers,[`pregunta_${i+1}`]:v})}/>)}</div><div style={{marginTop:18,textAlign:"right"}}><Button variant="primary" onClick={save}>Guardar audio</Button>{status&&<p>{status}</p>}</div></div></section>}

function HistorySection(){const[sessions,setSessions]=useState(()=>safeReadSessions());const[sheetsUrl,setSheetsUrlState]=useState(()=>getSheetsUrl());const[configStatus,setConfigStatus]=useState("");const downloadFile=(content,filename,type)=>{const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url)};const exportData=()=>downloadFile(JSON.stringify(sessions,null,2),"registro_respuestas_portal.json","application/json");const exportCsv=()=>downloadFile(`${String.fromCharCode(0xfeff)}${buildCsvFromSessions(sessions)}`,"registro_respuestas_portal.csv","text/csv;charset=utf-8");const clear=()=>{if(confirm("¿Borrar todo el historial?")){localStorage.removeItem("portal_sessions");setSessions([])}};const saveSheetsConfig=()=>{setSheetsUrl(sheetsUrl);setConfigStatus("URL de Google Sheets guardada.")};const resendAllToSheets=async()=>{setConfigStatus("Reenviando sesiones...");for(const s of sessions)await sendSessionToGoogleSheets(s);setConfigStatus("Sesiones reenviadas.")};const logout=()=>{localStorage.removeItem("portal_patient_code");window.location.reload()};return <section className="section"><SectionTitle icon={History} title="9. Registro y comparación" subtitle="Guarda localmente y envía automáticamente a Google Sheets."/><div className="card"><h3>Paciente activo: {getPatientCode()}</h3><Button variant="outline" onClick={logout}>Cambiar paciente</Button></div><div className="card" style={{marginTop:16}}><h3>Conexión con Google Sheets</h3><div className="config-row"><input value={sheetsUrl} onChange={(e)=>setSheetsUrlState(e.target.value)} placeholder="https://script.google.com/macros/s/.../exec"/><Button variant="primary" onClick={saveSheetsConfig}>Guardar URL</Button><Button variant="outline" onClick={resendAllToSheets}>Reenviar historial</Button></div>{configStatus&&<p>{configStatus}</p>}</div><div style={{display:"flex",flexWrap:"wrap",gap:10,margin:"16px 0"}}><Button variant="outline" onClick={()=>setSessions(safeReadSessions())}>Actualizar</Button><Button variant="outline" onClick={exportData}><Download size={16}/> Exportar JSON</Button><Button variant="outline" onClick={exportCsv}><Download size={16}/> Exportar CSV</Button><Button variant="danger" onClick={clear}><Trash2 size={16}/> Borrar historial</Button></div>{sessions.length===0?<div className="card">Aún no hay sesiones guardadas.</div>:sessions.map((s)=><div className="card" key={s.id} style={{marginBottom:12}}><h3>{s.module}: {s.activityTitle}</h3><p><b>Fecha:</b> {s.date} · <b>Paciente:</b> {s.patientCode} · <b>Puntuación:</b> {s.score||"-"} / {s.maxScore||"-"}</p><details><summary>Ver datos</summary><pre>{JSON.stringify(s,null,2)}</pre></details></div>)}</section>}

export default function App(){const[patientCode,setPatientCode]=useState(getPatientCode());const tabs=[["explicacion","Explicación",Sparkles],["algoritmos","Algoritmos",ClipboardList],["ejercicios","Ejercicios",Calculator],["lectura","Lectura",PenLine],["planificacion","Planificación",ListChecks],["memoria","Memoria",Brain],["atencion","Atención",Search],["audio","Audio",Ear],["historial","Historial",History]];const[tab,setTab]=useState("explicacion");const Current=useMemo(()=>({explicacion:<Explanation/>,algoritmos:<Algorithms/>,ejercicios:<MathPractice/>,lectura:<Reading/>,planificacion:<Planning/>,memoria:<Memory/>,atencion:<Attention/>,audio:<AudioExercises/>,historial:<HistorySection/>}[tab]),[tab]);if(!patientCode)return <LoginGate onLogin={setPatientCode}/>;return <div className="app"><div className="container"><header><motion.div className="hero" initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}}><div className="floating-symbol">∫</div><div className="hero-badge"><Sparkles size={16}/> Portal interactivo terapéutico</div><h1>Funciones, lectura y entrenamiento cognitivo</h1><div className="hero-tags"><span><Zap size={16}/> Retos visuales</span><span><Target size={16}/> Vida diaria</span><span><Rocket size={16}/> Progreso por sesión</span><span><UserRound size={16}/> {patientCode}</span></div></motion.div><nav className="nav">{tabs.map(([id,label,Icon])=><Button key={id} variant={tab===id?"primary":"plain"} onClick={()=>setTab(id)}><Icon size={17}/>{label}</Button>)}</nav></header><motion.main key={tab} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{duration:.25}}>{Current}</motion.main><footer className="footer">Prototipo educativo/terapéutico. Usa códigos de paciente en lugar de datos sensibles.</footer></div></div>}
